# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Reduction Guide
author: Jess Speedie
logo: abaur.png
copyright: '2024'

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Disable building files that aren’t in the Table of Contents
only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: reduction-guide.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/jjspeedie/guide.2021.1.00690.S  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  favicon: "abaur.png"  # A path to a favicon image

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - amsmath
    - colon_fence
    # - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context

sphinx:
  extra_extensions:
    - sphinx.ext.intersphinx
  config:
    intersphinx_mapping:
      python: ('https://docs.python.org/3', None)
    nitpicky: true
    nitpick_ignore:
      - 'py:class reference not found'
